### ISSUE TITLE
Expose Prometheus OAuth2 in MSO

### ISSUE THREAD

**Issue by tsisodia10** [rhobs/monitoring-stack-operator#144]
Prometheus with many authentication mechanisms like `TLS` and `Basic auth` has released another `HTTP` authentication mechanism: `OAuth2.0 / OpenID Connect` with the new release of `2.27` onwards. This is a client-side authentication, so Prometheus can fetch access tokens using the `OAuth 2.0 Client Credentials Grant` and use them to talk to the targets. This issue is concerned with exposing `oauth2` on remote write.

We need to leverage Prometheus `OAuth2` to make sure `tokens` are not expired and also, `OAuth2` spec would have the credentials to talk to the targets.

**Comment by cmwylie19** [comment]
@sthaha Is this a feature that you all see yourselves using? Is this a good feature for the upstream? We wanted to check with you all first. Thanks!

**Comment by sthaha** [comment]
@tsisodia10 @cmwylie19 I am not sure follow what the feature request really is ... But as @tsisodia10 pointed out we are in the process of upgrading Prometheus Operator to 0.55.1 and that should bring in the OAuth to the RemoteWrite Spec which in reality does exist in the cluster but the types used by MSO from Prometheus Operator is that of 0.50 

In relation to the usage, I am not sure if monitoring stack itself including the operator would be using this since the primary target is to deploy the stack and help configure it which is mostly done through Prometheus Operator.

 The addons on OSD may choose to configure remote write but that is beyond the scope of the Monitoring Stack Operator. 

cc: @jan--f

**Comment by cmwylie19** [comment]
> 

Ah, you are exactly right @sthaha . That was an oversight on my part. Since `oauth2` is embedded in the `remoteWrite` this is not a necessary. Thanks! We are closing this issue.

**Comment by sthaha** [comment]
@cmwylie19 no worries :) .. Thank you for confirming 🙇
